services:
  db:
    image: mysql:8.0.29
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: rest_with_springboot_matheus
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3306
    ports: 
      - 3308:3308
    expose:
      - 3308
    networks:
      - matheus-network

  rest-with-springboot-matheus:
    image: matheusluizago/rest_with_springboot_matheus
    restart: always
    build: 
      context: ./rest-with-springboot-and-java
      dockerfile: Dockerfile
    working_dir: "/mnt/c/Users/USER/Documents/estagio-uol/Trilha-AWS-Compass/semana-10/projeto/rest-with-springboot-and-java"

    environment: 
      TZ: America/Sao_Paulo
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/rest_with_springboot_matheus?useTimezone=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports: 
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - matheus-network

networks:
  matheus-network:
    driver: bridge
