name: Continuous Integration with Github Actions

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: List files
      run: ls -R  # Listar arquivos para verificar o caminho do pom.xml

    - name: Login to Docker Hub
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build Application JAR
      working-directory: ./rest-springboot-docker/rest-with-springboot-and-java
      run: mvn clean package -DskipTests

    - name: Docker Compose Build
      working-directory: ./rest-springboot-docker
      run: docker compose build

    - name: Push to Docker Hub Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/rest_with_springboot_matheus:latest ${{ secrets.DOCKER_USERNAME }}/rest_with_springboot_matheus:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/rest_with_springboot_matheus:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/rest_with_springboot_matheus:latest
